/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/shoe.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Model(props) {
  const { nodes, materials } = useGLTF('/ririana-web/shoe.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="laces" geometry={nodes.shoe.geometry} material={materials.laces} material-color={"#D65B41"}/>
      <mesh name="mesh"  geometry={nodes.shoe_1.geometry} material={materials.mesh}material-color={"#ADD8E6"} />
      <mesh name="caps"  geometry={nodes.shoe_2.geometry} material={materials.caps}material-color={"#FFFFFF"} />
      <mesh name="inner" geometry={nodes.shoe_3.geometry} material={materials.inner}material-color={"white"} />
      <mesh name="sole"  geometry={nodes.shoe_4.geometry} material={materials.sole} material-color={"white"}/>
      <mesh name="stripes" geometry={nodes.shoe_5.geometry} material={materials.stripes} material-color={"blue"}/>
      <mesh name= "band" geometry={nodes.shoe_6.geometry} material={materials.band} material-color={"red"}/>
      <mesh name="patch" geometry={nodes.shoe_7.geometry} material={materials.patch}material-color={"blue"} />
    </group>
  )
}

useGLTF.preload('/ririana-web/shoe.gltf')
